stages:
  - build
  - test
  - deploy

# Frontend jobs
build_frontend:
  stage: build
  image: cypress/browsers:latest
  tags:
    - hva
  script:
    - cd frontend
    - npm install
    - npm run build

test_frontend:
  stage: test
  image: cypress/browsers:node14.17.0-chrome91-ff89
  tags:
    - hva
  script:
    - cd frontend
    - npm install
    - nohup npm run start &  # Start de server op de achtergrond
    - sleep 10               # Wacht even om de server tijd te geven om te starten
    - npx cypress run        # Voer Cypress tests uit
    
deploy_frontend:
  stage: deploy
  tags:
    - hva
  script:
    - echo "Deploy frontend"
  only:
    - main